In [2]:
import torch
import numpy as np

### pytorch datatypes - tensors

In [3]:
# pytorch scalar, vector, matrix veya tensorlerin hepsini tensor sınıfında tutar.
torch.tensor(10)

tensor(10)

In [4]:
torch.tensor([10,20])

tensor([10, 20])

In [5]:
scalar = torch.tensor(10)
type(scalar)

torch.Tensor

In [6]:
print(scalar + 5 )
print(scalar - 10)
print(scalar * 3)
print(scalar/2)

tensor(15)
tensor(0)
tensor(30)
tensor(5.)


In [7]:
scalar.dim() # Kaç boyutlu olduğunu gösterir

0

In [8]:
scalar.shape

torch.Size([])

In [9]:
scalar.item()

10

In [10]:
type(scalar.item())

int

In [11]:
numpy_int =np.int32(10)
numpy_int

np.int32(10)

In [12]:
numpy_int + 10

np.int32(20)

In [13]:
numpy_int - 10

np.int32(0)

In [14]:
numpy_int * 3

np.int32(30)

In [15]:
numpy_int / 2

np.float64(5.0)

In [16]:
scalar_from_np = torch.tensor(numpy_int)
scalar_from_np

tensor(10, dtype=torch.int32)

In [17]:
scalar_from_np.dtype

torch.int32

In [18]:
scalar.dtype # Default olarak 64 bit oluşturuluyor.

torch.int64

In [19]:
new_scalar = torch.tensor(25, dtype=torch.int32) 
new_scalar + 17

tensor(42, dtype=torch.int32)

In [20]:
new_scalar.dtype

torch.int32

In [21]:
tensor_float = torch.tensor(3.14)
tensor_float

tensor(3.1400)

In [22]:
tensor_float.dtype

torch.float32

In [23]:
tensor_float_64 = torch.tensor(3.14,dtype=torch.float64)
tensor_float_64

tensor(3.1400, dtype=torch.float64)

In [24]:
tensor_float_64 * 2 

tensor(6.2800, dtype=torch.float64)

In [25]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [26]:
vector.dim()

1

In [27]:
vector.ndim

1

In [28]:
vector.shape

torch.Size([2])

In [29]:
vector = torch.tensor([1,2,3])
vector.dim()

1

In [ ]:
vector.shape # tek boyut içerisindeki eleman sayısını verir.

torch.Size([3])

In [ ]:
# count of [ -> dimension
# count elements -> shape
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [33]:
matrix.dim()

2

In [34]:
matrix.shape

torch.Size([2, 2])

In [35]:
tensor_example= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor_example.dim()

3

In [37]:
tensor_example.shape

torch.Size([2, 3, 3])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False) 
# dtype=None ise default değerini verir.
# device -> cpu ile mi gpu ile mi calısıcagımız
# reqires_grad -> gradient'in hesaplanıp hesaplanmayacağıdır.
float_32_tensor.dtype

torch.float32