In [1]:
import torch
import numpy as np

In [2]:
random_array = np.random.randn(3,5)
random_array

array([[ 1.45966439, -0.07283735, -0.66604333, -0.05589107,  0.18613371],
       [ 0.20742526,  0.51507678,  0.24550508,  0.01863289,  0.32115644],
       [-0.89120834,  0.56176239, -0.54590975, -0.73566716, -0.68033326]])

In [3]:
type(random_array)

numpy.ndarray

In [4]:
random_array.shape

(3, 5)

In [5]:
random_array.ndim

2

In [6]:
random_matrix = torch.rand(size=(3,5))
random_matrix

tensor([[0.8168, 0.0583, 0.0080, 0.5217, 0.9428],
        [0.5942, 0.7285, 0.6090, 0.3536, 0.6914],
        [0.7378, 0.0310, 0.0156, 0.9604, 0.2763]])

In [7]:
random_matrix.ndim

2

In [9]:
random_matrix.shape

torch.Size([3, 5])

In [10]:
random_matrix.dtype

torch.float32

In [11]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.7597, 0.3083, 0.4446],
         [0.2853, 0.7985, 0.8138],
         [0.4147, 0.7607, 0.1911],
         ...,
         [0.5178, 0.9391, 0.5065],
         [0.9331, 0.6609, 0.2178],
         [0.9343, 0.3204, 0.8995]],

        [[0.5004, 0.0216, 0.4699],
         [0.7836, 0.3135, 0.0661],
         [0.3499, 0.9567, 0.2704],
         ...,
         [0.0802, 0.6006, 0.1038],
         [0.0277, 0.6666, 0.0947],
         [0.3367, 0.2949, 0.6101]],

        [[0.9096, 0.2896, 0.1659],
         [0.0619, 0.5214, 0.4901],
         [0.2338, 0.9400, 0.7679],
         ...,
         [0.7966, 0.5636, 0.4724],
         [0.7061, 0.3613, 0.6403],
         [0.1058, 0.1966, 0.0064]],

        ...,

        [[0.9041, 0.3601, 0.8484],
         [0.3089, 0.4408, 0.7130],
         [0.0902, 0.6545, 0.6231],
         ...,
         [0.8729, 0.7721, 0.2780],
         [0.9815, 0.1993, 0.9966],
         [0.0360, 0.2373, 0.8594]],

        [[0.1310, 0.8539, 0.4879],
         [0.6579, 0.2476, 0.4499],
         [0.

In [12]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [13]:
random_image_tensor.ndim

3

In [15]:
zeros = torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
ones = torch.ones(size=(3,1))
ones

tensor([[1.],
        [1.],
        [1.]])

In [20]:
vector_with_arange = torch.arange(start=0,end=10,step=2)
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [22]:
similar_ones = torch.ones_like(input=vector_with_arange)
similar_ones

tensor([1, 1, 1, 1, 1])

In [24]:
x_tensor = torch.tensor([1,2,3])
x_tensor + 15 

tensor([16, 17, 18])

In [25]:
x_tensor * 12

tensor([12, 24, 36])

In [27]:
x_tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [28]:
x_tensor.subtract(10)

tensor([-9, -8, -7])

In [29]:
x_tensor.multiply(10)

tensor([10, 20, 30])

In [30]:
x_tensor.add(20)

tensor([21, 22, 23])

In [32]:
x_tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [33]:
x_tensor * x_tensor

tensor([1, 4, 9])

In [34]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [35]:
x_tensor - x_tensor

tensor([0, 0, 0])

In [36]:
x_tensor / x_tensor

tensor([1., 1., 1.])

In [ ]:
y_tensor = torch.tensor([4,5])
# y_tensor + x_tensor # boyut hatası verir.

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0