In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.tensor([1,2,3])

In [3]:
tensor * tensor 

tensor([1, 4, 9])

In [ ]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [ ]:
matrix * matrix # hala element by element çarpımı yapıyor.

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [ ]:
matrix @ matrix  # Matrix çarpımı için ---> @ işareti kullanılır.

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [ ]:
torch.matmul(matrix, matrix) # matmul ile de matrix multiplication yapılabilir.

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [ ]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor2 = torch. tensor([[8,9],
                         [10,11],
                         [12,13]])
tensor1 @ tensor2 #boyut uyumsuzluğu

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [9]:
tensor1 @ tensor2.T

tensor([[ 26,  32,  38],
        [ 60,  74,  88],
        [ 94, 116, 138]])

In [10]:
A = torch.tensor([[1,2,3]])
A.shape

torch.Size([1, 3])

In [11]:
A.ndim

2

In [13]:
B = torch.tensor([[1],[2],[3]])
B.shape

torch.Size([3, 1])

In [14]:
B.ndim

2

In [17]:
result = A @ B 

In [18]:
result

tensor([[14]])

In [19]:
result.shape

torch.Size([1, 1])

In [20]:
result.ndim

2