In [34]:
import torch

In [35]:
tensor = torch.arange(0,50,5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
tensor.min()

tensor(0)

In [37]:
tensor.max()

tensor(45)

In [38]:
tensor.sum()

tensor(225)

In [39]:
tensor.median()

tensor(20)

In [41]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [42]:
# ortalamayı almak için dtype'ı float yapmalıyız.
tensor = tensor.type(torch.float)
tensor.mean()

tensor(22.5000)

In [43]:
# argmax, argmin
tensor.argmax() # maximum değerin indeksi

tensor(9)

In [44]:
tensor.argmin() # minimum değerin indeksi

tensor(0)

In [45]:
tensor[9]

tensor(45.)

### manipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [46]:
x = torch.arange(1,10,1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x.shape

torch.Size([9])

In [48]:
x.ndim

1

In [49]:
# reshaping
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
x_reshaped.shape

torch.Size([1, 9])

In [51]:
x_reshaped.ndim

2

In [52]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [54]:
x_reshaped[0] = 20
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [ ]:
x # x_reshaped'teki ilk elemanı değiştiirnce x'teki ilk elemande değişiyor.

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
# view
x_view = x.view(9,1)
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [58]:
x_view[0] = 10
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [59]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
# view -> contigious tensorlarla çalışır sadece.
# non-contiguous: bellekte ardışık saklanmayan tensorlerdir.
# contiguous: bellekte ardışık (yan-yana) saklanan tensorlerdir.

In [63]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])
x.is_contiguous()

True

In [64]:
y = x.t()
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [65]:
y.is_contiguous()

False

### Stacking

In [66]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [67]:
# stacking yaparken hepsi aynı dimension'da olmalı
torch.stack([x,x,x,x],dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [68]:
torch.stack([x,x,x,x],dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

### squeeze & unsqueeze

In [69]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [70]:
x.shape

torch.Size([2, 3])

In [72]:
x.ndim

2

In [73]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [74]:
x.squeeze().shape

torch.Size([2, 3])

In [75]:
x.squeeze().ndim

2

In [ ]:
# squeeze fonksiyonu eğer yapabiliyorsa boyutunu azaltır
# squeeze() ile gereksiz bütün boyutları atar sadece 1 tane değil.
x = torch.tensor([[1,2,3]])
x.shape

torch.Size([1, 3])

In [78]:
x.ndim

2

In [79]:
x.squeeze()

tensor([1, 2, 3])

In [80]:
x.squeeze().shape

torch.Size([3])

In [81]:
x.squeeze().ndim

1

In [82]:
# unsqueeze boyut artırmak için kullanılır
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
# dimension belirtmeliyiz
x.unsqueeze(dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [84]:
x.unsqueeze(dim=0).ndim

3

### permute

In [ ]:
# sırayı değiştiriyoruz boyut kaybı yok.
x = torch.rand(size=(224,224,3))
x.shape

torch.Size([224, 224, 3])

In [86]:
x_permuted = x.permute(2,0,1) # axis 0->1 1->2 2->0

In [87]:
x_permuted.shape

torch.Size([3, 224, 224])

### indexing & slicing

In [89]:
a = torch.arange(1,10,1)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a = a.reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [95]:
a[0][0][0]

tensor(1)

In [96]:
a.shape

torch.Size([1, 3, 3])

In [97]:
a.ndim

3

In [ ]:
# ilk boyuttaki tüm değerleri alıp row ve column'ın 0.'sını al -> a[:,0,0]
a[:,0,0]

tensor([1])

In [100]:
a[:,1,0]

tensor([4])

In [ ]:
# sadece ilk column'ı al
a[:,:,0]

tensor([[1, 4, 7]])

In [102]:
#sadece ilk row'u al
a[:,0,:]

tensor([[1, 2, 3]])

### random seed

In [ ]:
RANDOM_SEED = 42 # herhangi bir rakam olabilir
torch.manual_seed(RANDOM_SEED) # artık yanı rakamlar üretilicek.
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])