In [5]:
import torch

In [6]:
# requirements.txt dosyasından torch yüklendiğinde bazen default olarak cpu yüklenmesi gerçekleşebilir.
# böyle bir durumda torch ve torchvision kütüphanelerini silip manuel olarak terminalden gpu'lu versioynu yükleyebiliirz.
torch.cuda.is_available() # Bilgisayarda cuda ile çalışan bir gpu'muz var mı diye bakar.

True

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
device

'cuda'

### Tensorları taşıma

In [9]:
tensor = torch.tensor([1,2,3])

In [12]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor.device # default olarak cpu type'ında gelir.

device(type='cpu')

In [11]:
# manuel taşıma
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [13]:
tensor.numpy()

array([1, 2, 3])

In [ ]:
tensor_on_gpu.numpy()
# tensorler gpu ise numpy'a çeviremeyiz. cpu olması lazım

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_on_gpu.cpu().numpy() # cpu'ya cevirip numpy'a cevirebiliriz.

array([1, 2, 3])

In [ ]:
# context manager kullanarak taşıma with keyboardı ile
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)
tensor2.device
# type olarak gpu'da oluştu

device(type='cuda', index=0)

In [ ]:
layer.weight.device
# aynı şekilde buda gpu'da oluştu.

device(type='cuda', index=0)

In [ ]:
tensor3= torch.tensor([4,5,6])
tensor3.device # with keyboard'ının dısında olusturdgumuz ıcın default olarak cpu ile oluşturuldu.

device(type='cpu')

In [ ]:
# default'ını gpu olarak ayarladık fakat bundan önce oluşturulan cpu tensorlar gpu'ya dönmez
torch.set_default_device(device)
tensor4 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(10,20)
tensor4.device

device(type='cuda', index=0)

In [22]:
layer2.weight.device

device(type='cuda', index=0)

In [23]:
tensor3.device

device(type='cpu')