In [2]:
import numpy as np

In [3]:
my_list = [10,20,30,40]
type(my_list)

list

In [4]:
my_numpy_array = np.array(my_list)
type(my_numpy_array)

numpy.ndarray

In [5]:
my_numpy_array.max()

np.int64(40)

In [9]:
print(np.ones(3),np.zeros(4),np.random.random(5))
# np.random.random belirtilmediği sürece 0 ile 1 arasında üretilir

[1. 1. 1.] [0. 0. 0. 0.] [0.55033043 0.02233159 0.16187142 0.54987264 0.2612129 ]


### array arithmetic

In [14]:
my_list1 = [1,2]
my_list2 = [2,3]
print(my_list1+my_list2)
# Yan yana koyar.

[1, 2, 2, 3]


In [ ]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)
print(my_numpy_array1 + my_numpy_array2)

[3 5]


In [18]:
print(my_numpy_array1*my_numpy_array2)
print(my_numpy_array1/my_numpy_array2)
print(my_numpy_array1-my_numpy_array2)
print(my_numpy_array1 * 5)


[2 6]
[0.5        0.66666667]
[-1 -1]
[ 5 10]


In [19]:
other_array = np.array([10,20,30,40,50])
print(other_array.min())
print(other_array.sum())

10
150


### Indexing & arange

In [ ]:
print(list(range(0,10)))
print(np.arange(0,10)) # üstteki range fonksiyonunun numpy hali gibi düşünebiliriz.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np_array = np.arange(0,10)
print(np_array[0],"---",np_array[-1],"---",np_array[1:4],"---",np_array[::-1])

0 --- 9 --- [1 2 3] --- [9 8 7 6 5 4 3 2 1 0]


In [ ]:
# random
np.random.randn(4,2) # 4 row, 2 columnluk matris olusturur

array([[ 0.21102618, -1.72920698],
       [-0.40694953, -1.5945632 ],
       [ 0.39691948,  0.23432165],
       [-0.35674861, -0.58940526]])

In [28]:
np.random.randint(1,300,5) # 1-300 arası 5 tane rastgele sayı verir.

array([271, 173, 289, 296, 266], dtype=int32)