In [1]:
import numpy as np

In [7]:
my_matrix = [[5,10],[1,2]]
print(my_matrix[0],"---",my_matrix[0][1])

[5, 10] --- 10


In [9]:
numpy_matrix = np.array([[5,10],[1,2]])
print(numpy_matrix,"---",numpy_matrix[1][1])

[[ 5 10]
 [ 1  2]] --- 2


In [10]:
print(numpy_matrix.sum())

18


In [16]:
print(np.ones((2,3))) # 3 satır 2 sütunluk np.ones matrisi
print("\n")
print(np.zeros((3,5)))
print("\n")
print(np.random.random((3,2)))

[[1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0.83113433 0.8619496 ]
 [0.1374752  0.93577372]
 [0.98234439 0.03390979]]


###  matrix arithmetic

In [ ]:
first_array = np.array([[10,20],[15,20]])
second_array = np.array([[5,15],[25,35]])
print(first_array+second_array) # Matrix summatiation

[[15 35]
 [40 55]]


In [ ]:
third_array = np.array([[50,60]]) # 1 satır 2 sütunluk matris
print(first_array+third_array)
# Bu satırı first_array'in 2 satırıylada toplar. Normalde boyut uyumsuzluğu ama numpy bunu sağlıyor.

[[60 80]
 [65 80]]


In [22]:
fourth_array = np.array([[10,20,30,40,50]])
print(first_array+fourth_array)
# Bunu uyduramadığından typeError verir

ValueError: operands could not be broadcast together with shapes (2,2) (1,5) 

In [ ]:
fourth_array.shape # boyutlarını verir.

(1, 5)

### matrix multiplication

In [ ]:
first_array * second_array
# normal çarpma islemi yapar.

array([[ 50, 300],
       [375, 700]])

In [ ]:
first_matrix = np.array([[10,20,30]])
second_matrix = np.array([[2,3],[3,2],[2,3]])
print(first_matrix.shape,"---",second_matrix.shape)
print(first_matrix.dot(second_matrix)) # dot product.

(1, 3) --- (3, 2)
[[140 160]]
