In [14]:
import numpy as np

In [15]:
new_array = np.random.randint(1,100,20)
print(new_array)

[13 75 63 69 17  4 80 65 25 12 47 47  9 99 69 20 19 59 28 75]


In [16]:
new_array > 25

array([False,  True,  True,  True, False, False,  True,  True, False,
       False,  True,  True, False,  True,  True, False, False,  True,
        True,  True])

In [17]:
new_array[new_array>25] # new_array içindeki 25'ten büyük olanları gösteririz.

array([75, 63, 69, 80, 65, 47, 47, 99, 69, 59, 28, 75], dtype=int32)

### transpose & reshape islemleri

In [18]:
matrix_array = np.array([[10,20],[20,30],[30,40]])
matrix_array.shape

(3, 2)

In [19]:
matrix_array.transpose() # transpose islemi

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
matrix_array.T # Transpose islemidir

array([[10, 20, 30],
       [20, 30, 40]])

In [23]:
random_array = np.random.random((6,1))
random_array.shape

(6, 1)

In [ ]:
random_array.reshape(2,3) # Yeni boyut verebiliriz

array([[0.7540091 , 0.82440855, 0.32009066],
       [0.93631548, 0.7087667 , 0.08893571]])

In [ ]:
# z-score hesaplama
data = np.array([10,12,13,15,18,25,100,105])

In [ ]:
mean = np.mean(data)
mean

np.float64(37.25)

In [ ]:
std = np.std(data)
std # standard sapma

np.float64(37.9333296719389)

In [32]:
z_scores = (data - mean) / std
z_scores # outlier(aykırı) değerlerin skoru yüksek çıktı.

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [35]:
z_scores[z_scores>1] # outlier değer gösterimi

array([1.65421809, 1.78602829])

In [37]:
data[z_scores>1] # outlierlar

array([100, 105])

### mat equations

In [38]:
# 2x + 3y = 8 and 5x + 7y = 19

In [44]:
# coefficent matrix
coef = np.array([[2,3],[5,8]])
# constant matrix
cons = np.array([8,19])
# solution
solution = np.linalg.solve(coef,cons)
print(f"x:{solution[0]}-- y:{solution[1]}")

x:6.999999999999995-- y:-1.9999999999999962
